apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storageclass.yaml
  - configmap.yaml
  - deployment-portail.yaml
  - deployment-api.yaml
  - statefulset-cache.yaml
  - services.yaml
  - ingress.yaml
  - hpa.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: foodtrack
    includeSelectors: true
    includeTemplates: true
